#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
default_manifest="${CHAOS_MANIFEST:-$script_dir/node-latency-chaos.yaml}"
kubectl_bin="${KUBECTL:-kubectl}"
workload_namespace="${WORKLOAD_NAMESPACE:-default}"
node_group_label="${NODE_GROUP_LABEL:-topology.kubernetes.io/zone}"
node_selector="${NODE_SELECTOR:-}"
cross_zone_latency="${CROSS_ZONE_LATENCY:-50ms}"
cross_zone_bandwidth="${CROSS_ZONE_BANDWIDTH:-10mbps}"
bandwidth_limit="${BANDWIDTH_LIMIT:-20971520}"
bandwidth_buffer="${BANDWIDTH_BUFFER:-10000}"
jitter="${JITTER:-0ms}"
correlation="${CORRELATION:-0}"

# Set OBSERVER_NAMESPACE to an empty string to omit observer traffic rules.
observer_namespace="${OBSERVER_NAMESPACE-observability}"
observer_label_key="${OBSERVER_LABEL_KEY:-app}"
observer_label_value="${OBSERVER_LABEL_VALUE:-mentat}"

usage() {
  cat <<EOF
Usage:
  $(basename "$0") generate [MANIFEST]
  $(basename "$0") deploy [MANIFEST]
  $(basename "$0") apply [MANIFEST ...]
  $(basename "$0") delete [MANIFEST ...]

Commands:
  generate  Generate a cluster-specific Chaos Mesh manifest.
  deploy    Generate a manifest and immediately apply it.
  apply     Apply one or more generated manifests to the current cluster.
  delete    Delete resources defined by one or more generated manifests.

The default manifest is:
  $default_manifest

Generation is configured through the environment variables documented in
$script_dir/README.md. KUBECTL and standard kubectl variables such as
KUBECONFIG are honored by all commands.
EOF
}

require_manifest() {
  local manifest="$1"
  if [[ ! -f "$manifest" ]]; then
    echo "manifest not found: $manifest" >&2
    echo "generate it first with: $(basename "$0") generate \"$manifest\"" >&2
    exit 1
  fi
}

sanitize_name() {
  printf '%s' "$1" |
    tr '[:upper:]_' '[:lower:]-' |
    sed -E 's/[^a-z0-9-]+/-/g; s/^-+//; s/-+$//'
}

resource_name() {
  local name hash
  name="$(sanitize_name "$1")"
  if [[ "${#name}" -le 63 ]]; then
    printf '%s' "$name"
    return
  fi
  hash="$(printf '%s' "$name" | sha256sum | cut -c1-8)"
  printf '%s-%s' "${name:0:54}" "$hash"
}

emit_delay() {
  cat <<EOF
  delay:
    latency: "$cross_zone_latency"
    jitter: "$jitter"
    correlation: "$correlation"
EOF
}

emit_bandwidth() {
  cat <<EOF
  bandwidth:
    rate: "$cross_zone_bandwidth"
    limit: $bandwidth_limit
    buffer: $bandwidth_buffer
EOF
}

emit_metadata() {
  local name="$1"
  local namespace="$2"
  cat <<EOF
metadata:
  name: $name
  namespace: $namespace
  labels:
    app.kubernetes.io/name: node-latency-chaos
    app.kubernetes.io/managed-by: node-latency-chaos-injector
EOF
}

write_manifest() {
  local node_template
  local node_entry node_name node_ip node_group
  local source_entry source_node source_group
  local target_entry target_node target_ip target_group
  local name
  local -a nodes

  if [[ ! "$bandwidth_limit" =~ ^[1-9][0-9]*$ || "$bandwidth_limit" -gt 4294967295 ]]; then
    echo "BANDWIDTH_LIMIT must be an integer between 1 and 4294967295" >&2
    return 1
  fi
  if [[ ! "$bandwidth_buffer" =~ ^[1-9][0-9]*$ || "$bandwidth_buffer" -gt 4294967295 ]]; then
    echo "BANDWIDTH_BUFFER must be an integer between 1 and 4294967295" >&2
    return 1
  fi

  node_template='{{range .items}}{{.metadata.name}}{{"\t"}}{{range .status.addresses}}{{if eq .type "InternalIP"}}{{.address}}{{end}}{{end}}{{"\t"}}{{index .metadata.labels "'"$node_group_label"'"}}{{"\n"}}{{end}}'
  local selector_args=()
  if [[ -n "$node_selector" ]]; then
    selector_args=(-l "$node_selector")
  fi
  mapfile -t nodes < <(
    "$kubectl_bin" get nodes "${selector_args[@]}" -o "go-template=$node_template" |
      sort
  )

  if [[ "${#nodes[@]}" -lt 2 ]]; then
    echo "expected at least two Kubernetes nodes" >&2
    return 1
  fi

  for node_entry in "${nodes[@]}"; do
    IFS=$'\t' read -r node_name node_ip node_group <<<"$node_entry"
    if [[ -z "$node_ip" ]]; then
      echo "node $node_name has no InternalIP" >&2
      return 1
    fi
    if [[ -z "$node_group" || "$node_group" == "<no value>" ]]; then
      echo "node $node_name is missing label $node_group_label" >&2
      return 1
    fi
  done

  echo "# Generated by chaos-injector/chaos-injector.sh"
  echo "# Node groups: $node_group_label"
  echo "# Cross-zone latency: $cross_zone_latency jitter=$jitter correlation=$correlation"
  echo "# Cross-zone bandwidth: $cross_zone_bandwidth limit=$bandwidth_limit buffer=$bandwidth_buffer"
  echo "# Workload namespace: $workload_namespace"

  for source_entry in "${nodes[@]}"; do
    IFS=$'\t' read -r source_node _ source_group <<<"$source_entry"
    for target_entry in "${nodes[@]}"; do
      IFS=$'\t' read -r target_node _ target_group <<<"$target_entry"
      if [[ "$source_node" == "$target_node" || "$source_group" == "$target_group" ]]; then
        continue
      fi

      name="$(resource_name "node-delay-$source_node-to-$target_node")"

      cat <<EOF
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
EOF
      emit_metadata "$name" "$workload_namespace"
      cat <<EOF
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - $workload_namespace
    nodes:
      - $source_node
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - $workload_namespace
      nodes:
        - $target_node
EOF
      emit_delay

      # Bandwidth restriction disabled — re-enable when bandwidth chaos is needed
      # name="$(resource_name "node-bandwidth-$source_node-to-$target_node")"
      # cat <<'_EOF'
      # ---
      # apiVersion: chaos-mesh.org/v1alpha1
      # kind: NetworkChaos
      # _EOF
      # emit_metadata "$name" "$workload_namespace"
      # cat <<_EOF
      # spec:
      #   action: bandwidth
      #   mode: all
      #   selector:
      #     namespaces:
      #       - $workload_namespace
      #     nodes:
      #       - $source_node
      #   direction: to
      #   target:
      #     mode: all
      #     selector:
      #       namespaces:
      #         - $workload_namespace
      #       nodes:
      #         - $target_node
      # _EOF
      # emit_bandwidth
    done
  done

  if [[ -z "$observer_namespace" ]]; then
    return
  fi

  echo "# Observer namespace: $observer_namespace ($observer_label_key=$observer_label_value)"
  for source_entry in "${nodes[@]}"; do
    IFS=$'\t' read -r source_node _ source_group <<<"$source_entry"
    for target_entry in "${nodes[@]}"; do
      IFS=$'\t' read -r target_node target_ip target_group <<<"$target_entry"
      if [[ "$source_node" == "$target_node" || "$source_group" == "$target_group" ]]; then
        continue
      fi

      name="$(resource_name "observer-delay-$source_node-to-$target_node")"

      cat <<EOF
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
EOF
      emit_metadata "$name" "$observer_namespace"
      cat <<EOF
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - $observer_namespace
    nodes:
      - $source_node
    labelSelectors:
      $observer_label_key: $observer_label_value
  direction: to
  externalTargets:
    - $target_ip
EOF
      emit_delay

      # Bandwidth restriction disabled — re-enable when bandwidth chaos is needed
      # name="$(resource_name "observer-bandwidth-$source_node-to-$target_node")"
      # cat <<'_EOF'
      # ---
      # apiVersion: chaos-mesh.org/v1alpha1
      # kind: NetworkChaos
      # _EOF
      # emit_metadata "$name" "$observer_namespace"
      # cat <<_EOF
      # spec:
      #   action: bandwidth
      #   mode: all
      #   selector:
      #     namespaces:
      #       - $observer_namespace
      #     nodes:
      #       - $source_node
      #     labelSelectors:
      #       $observer_label_key: $observer_label_value
      #   direction: to
      #   externalTargets:
      #     - $target_ip
      # _EOF
      # emit_bandwidth
    done
  done
}

generate() {
  local manifest="${1:-$default_manifest}"
  local temporary_manifest="${manifest}.tmp"

  if [[ $# -gt 1 ]]; then
    echo "generate accepts at most one manifest path" >&2
    usage >&2
    exit 2
  fi

  trap 'rm -f -- "$temporary_manifest"' RETURN
  write_manifest >"$temporary_manifest"
  mv -- "$temporary_manifest" "$manifest"
  trap - RETURN
  echo "generated $manifest"
}

deploy() {
  local manifest="${1:-$default_manifest}"

  if [[ $# -gt 1 ]]; then
    echo "deploy accepts at most one manifest path" >&2
    usage >&2
    exit 2
  fi

  generate "$manifest"
  apply_manifests "$manifest"
}

apply_manifests() {
  local manifests=("$@")
  if [[ ${#manifests[@]} -eq 0 ]]; then
    manifests=("$default_manifest")
  fi

  for manifest in "${manifests[@]}"; do
    require_manifest "$manifest"
    "$kubectl_bin" apply -f "$manifest"
  done
}

delete_manifests() {
  local manifests=("$@")
  if [[ ${#manifests[@]} -eq 0 ]]; then
    manifests=("$default_manifest")
  fi

  for manifest in "${manifests[@]}"; do
    require_manifest "$manifest"
    "$kubectl_bin" delete --ignore-not-found=true -f "$manifest"
  done
}

command="${1:-}"
if [[ $# -gt 0 ]]; then
  shift
fi

case "$command" in
  generate)
    generate "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  apply)
    apply_manifests "$@"
    ;;
  delete)
    delete_manifests "$@"
    ;;
  help | --help | -h)
    usage
    ;;
  '')
    usage >&2
    exit 2
    ;;
  *)
    echo "unknown command: $command" >&2
    usage >&2
    exit 2
    ;;
esac
